### ISSUE TITLE
dividir em diretórios

### ISSUE THREAD

**Issue by crgimenes** [crgimenes/grupo-estudos-golang#63]
Estamos começando a adicionar conteudo mais avançado como acesso a banco de dados, filas, etc.

Talvez seja interessante dividir o conteudo em diretórios para não ficar tudo na raiz e agrupar de forma mais logica.

Exemplo:
/code para o core da linguagem
/db para bancos de dados
/queue para filas

Então ficaria `/db/postgresql`, `/db/sqlite`, `/db/mysql`, e assim por diante.

Na raiz de cada diretorio colocamos um `README.md` mais detalhado como já fazemos com os outros exemplos. Mas mesmo assim  no `README.md` principal colocamos o caminho completo para cada entrada nos subdiretorios para o usário não ter que ficar navegando em subitens e termos um indice completo logo na primeira pagina.

**Comment by developerfred** [comment]
@crgimenes não acha melhor fazer esta divisão em  um server-side?

**Comment by crgimenes** [comment]
> @crgimenes não acha melhor fazer esta divisão em um server-side?

Não entendi o que você quer dizer com server-side. Você diz em uma pagina do grupo? 
Se for isso temos uma que alias ta bem parada.
A ideia é tentar organizar melhor para não ficar tudo encavalado em uma lista enorme no README.

**Comment by eduardosatrini** [comment]
Acho que isso deveria ser aplicado, ta dificultando um pouco chegar no README de forma mais rápida, então separar em diretórios e subdiretórios que façam sentido é uma boa.

**Comment by crgimenes** [comment]
Verdade, tô tentando arrumar algum tempo não só para o repo mas para o site também.
