### ISSUE TITLE
Criar diretório de exemplos e revisar eles

### ISSUE THREAD

**Issue by renanbastos93** [crgimenes/grupo-estudos-golang#66]
Devemos revisar todos os exemplos e atualizar para o `go.mod`, além disso devemos ajustar cabeçalho do hugo conforme o último encontro dia 15/10/2020 substituindo `+` para `-`. Importante cada pull requeste aberto vincular com essa issue.

TODO:
- [x] Criar diretório de exemplos
- [x] array
- [ ] ascii7
- [ ] assets
- [ ] autoupdate
- [ ] beanstalk
- [ ] botao_e_LED
- [ ] build_tags
- [ ] channel
- [ ] context
- [ ] cpp
- [ ] crawler
- [ ] crc
- [ ] data-race
- [ ] db
- [ ] defer
- [ ] doomfire
- [ ] env
- [ ] error
- [ ] exec
- [ ] for
- [ ] funcoes
- [ ] go_com_c
- [ ] goaleatorio
- [ ] goalfabeto
- [ ] godoc
- [ ] godolar
- [ ] goenglish
- [ ] goroutines
- [ ] goroutines_waitgroup
- [ ] goto
- [ ] http
- [ ] http_get
- [ ] http_middleware
- [ ] http_templates
- [ ] interface
- [ ] interface_closer
- [ ] ioutil
- [ ] json
- [ ] lua
- [ ] map
- [ ] myfs
- [ ] net
- [ ] ola_mundo
- [ ] package
- [ ] plugin
- [ ] ponteiros
- [ ] protobuf
- [ ] pwm
- [ ] quine
- [ ] ras
- [ ] rascunhos
- [ ] readline
- [ ] reflection
- [ ] regexp
- [ ] reverse_proxy
- [ ] select
- [ ] serial
- [ ] server
- [ ] sessions
- [ ] shadow
- [ ] signals
- [ ] slice
- [ ] sliceXarray
- [ ] smtp
- [ ] struct
- [ ] switch
- [ ] syncMap
- [ ] tcp
- [ ] testing
- [ ] time
- [ ] unixDomainSocket
- [ ] variaveis
- [ ] wikipedia
- [ ] xml
- [ ] zeroconf
- [ ] zip

**Comment by crgimenes** [comment]
Criei um branch V2 e um PR em WIP https://github.com/crgimenes/grupo-estudos-golang/pull/73
Movi todos os exemplos para o diretório "nao_tratado" e estou atualizando de lá. 
A ideia é já fazer a reorganização colocando os exemplos em um diretório "exemplos" para a lista não ficar toda na tela de uma vez quando a pessoa entra no repo.
